### PR TITLE
Durability - Fixed assemble-restored-session fn to recognize activation fns

### PR DESCRIPTION
**Pull request by nrayapati**
The below code doesn't propagate _activation-group-sort-fn_  and _activation-group-fn_, which throws exception.  This was introduced with https://github.com/rbrush/clara-rules/pull/219

Have updated function signature, hopefully no one else has started using this yet to effect the passivity. If the memory needs to be a parameter we can add it as an  option. Thoughts?

```clojure
(let [session (dur/assemble-restored-session rulebase
                                            (cre/local-memory rulebase
                                                                (clara.rules.engine.LocalTransport.)
                                                                activation-group-sort-fn
                                                                activation-group-fn
                                                                (dur/create-default-get-alphas-fn rulebase))
                                              opts))))))]
(cr/insert-all session initial-facts))
```

```clojure
#error {
 :cause "clojure.lang.PersistentVector cannot be cast to java.lang.Number"
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.Number, compiling:(NO_SOURCE_FILE:2:5)"
   :at [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3657]}
  {:type java.lang.ClassCastException
   :message "clojure.lang.PersistentVector cannot be cast to java.lang.Number"
   :at [clojure.lang.Util compare "Util.java" 152]}]
 :trace
 [[clojure.lang.Util compare "Util.java" 152]
  [synapse.clara$salience_group_activation_group_sort_fn invokeStatic "clara.clj" 650]
  [synapse.clara$salience_group_activation_group_sort_fn invoke "clara.clj" 647]
  [clara.rules.engine$options__GT_activation_group_sort_fn$fn__30425 invoke "engine.cljc" 1609]
  [clojure.lang.AFunction compare "AFunction.java" 47]
  [java.util.TreeMap getEntryUsingComparator "TreeMap.java" 376]
  [java.util.TreeMap getEntry "TreeMap.java" 345]
  [java.util.TreeMap
 get "TreeMap.java" 278]
  [clara.rules.memory.TransientLocalMemory add_activations_BANG_ "memory.cljc" 734]
  [clara.rules.engine.ProductionNode left_activate "engine.cljc" 263]
  [clara.rules.engine$eval28737$fn__28781$G__28723__28788 invoke "engine.cljc" 72]
  [clara.rules.engine$eval28737$fn__28781$G__28722__28796 invoke "engine.cljc" 72]
  [clara.rules.engine$propagate_items_to_nodes invokeStatic "engine.cljc" 120]
  [clara.rules.engine$propagate_items_to_nodes invoke "engine.cljc" 102]
  [clara.rules.engine.LocalTransport send_tokens "engine.cljc" 134]
  [clara.rules.engine.RootJoinNode right_activate "engine.cljc" 387]
  [clara.rules.engine$eval28818$fn__28819$G__28808__28826 invoke "engine.cljc" 80]
  [clara.rules.engine$eval28818$fn__28819$G__28807__28834 invoke "engine.cljc" 80]
  [clara.rules.engine$propagate_items_to_nodes invokeStatic "engine.cljc" 120]
  [clara.rules.engine$propagate_items_to_nodes invoke "engine.cljc" 102]
  [clara.rules.engine.LocalTransport send_elements "engine.cljc" 131]
  
[clara.rules.engine.AlphaNode alpha_activate "engine.cljc" 341]
  [clara.rules.engine.LocalSession insert "engine.cljc" 1500]
  [clara.rules$insert_all invokeStatic "rules.cljc" 21]
  [clara.rules$insert_all invoke "rules.cljc" 17]
```

### CODE REVIEW

**Comment by mrrodriguez** [comment]
clara.rules.durability.fressian Calls this function and this change would break that since you removed an argument from the signature. I'm not sure I'm understanding what the problem is either. The memory was intended to be passed in though, not created from scratch. See how clara.rules.durability.fressian is using it. 

The activation and alphas functions were just added on later was the idea since they weren't automatically serialized (not really serializable). 

Also it was intentional that the local memory was created via the constructor from scratch. Calling clara.rules.engine/local-memory does too much here. It doesn't only crest local memory, it "seeds" it with root tokens. Those will already have been done in the serialized memory we want to use later.

**Comment by mrrodriguez** [comment]
I don't really understand what the problem is from the example either. There are too many unknowns. What is in the argument opts? Where do you mean the activation group functions aren't propagated at? They are meant to be passed in as key-vals to opts.

**Comment by WilliamParker** [comment]
The presence of your custom activation group sort function in the stack trace suggests that it is indeed being passed in at least, so I'm not sure what you mean there.. perhaps we're talking about different things.  It seems to me like the next step here would be to look directly at what your activation group comparison function is getting as inputs that is causing a ClassCastException.  This could be done with printlines, a debugger (I use Cider's debugger, perhaps there are others), or putting the arguments in a piece of mutable state with something like 

````
(defn comparison-fn [x y]
  (put-in-global-state-somewhere-for-later-repl-examination [x y])
   (original-comparison-code x y))
````

**Comment by nrayapati** [comment]
@mrrodriguez @WilliamParker  here are more details, and with a debug statement at https://github.com/rbrush/clara-rules/blob/master/src/main/clojure/clara/rules/memory.cljc#L733
printing the below output, while deserializing the kb it prints just vec but after while insertion it print the vec with another vec in it, thats when its throwing an exception. 

````
...
dbg: (activation-group-fn production) = [-5 0]
dbg: (activation-group-fn production) = [-1 0]
dbg: (activation-group-fn production) = [-5 0]
dbg: (activation-group-fn production) = [-1 0]
dbg: (activation-group-fn production) = [[1 0] 0]
ClassCastException clojure.lang.PersistentVector cannot be cast to java.lang.Number  clojure.lang.Util.compare (Util.java:152)
````
```clojure
(defn activation-group-fn
  [rule-category-priorities]
  (fn salience-group-activation-group-fn [production]
    [(get rule-category-priorities
          (get-in production [:props :synapse/salience-group] :default))
     (get-in production [:props :salience] 0)]))

(defn activation-group-sort-fn
  [act1 act2]
  (compare act2 act1))

(def opts
{:activation-group-fn (activation-group-fn salience-groups)
   :activation-group-sort-fn activation-group-sort-fn})

(let [session (dur/assemble-restored-session rulebase
                                            (cre/local-memory rulebase
                                                                (clara.rules.engine.LocalTransport.)
                                                                activation-group-sort-fn
                                                                activation-group-fn
                                                                (dur/create-default-get-alphas-fn rulebase))
                                              opts))))))]
(cr/insert-all session initial-facts))
```

**Comment by nrayapati** [comment]
And I didn't realize that this being used internally, may I can change the signature back to it was and may be: 

```clojure
(defn assemble-restored-session
  "Builds a Clara session from the given rulebase and memory components.
   Note!  This function should not typically be used.  It is left public to assist in ISessionSerializer
          durability implementations.  Use clara.rules/mk-session typically to make rule sessions.

   Options can be provided via opts.
   These include:

   * :activation-group-sort-fn
   * :activation-group-fn
   * :get-alphas-fn (defaults to (create-default-get-alphas-fn rulebase))
   * :listeners (defaults to [])
   * :transport (defaults to clara.rules.engine.LocalTransport)

   If the options are not provided, they will default to the Clara session defaults.
   These are all described in detail in clara.rules/mk-session docs."
  [rulebase memory opts]
  (let [{:keys [listeners transport get-alphas-fn]} opts
        get-alphas-fn (or get-alphas-fn (create-default-get-alphas-fn rulebase))
        transport (or transport (clara.rules.engine.LocalTransport.))
        listeners (or listeners [])
        activation-group-sort-fn (eng/options->activation-group-sort-fn opts)
        activation-group-fn (eng/options->activation-group-fn opts)
        memory (or memory (eng/local-memory rulebase transport activation-group-sort-fn activation-group-fn get-alphas-fn))]
    
    (eng/assemble {:rulebase rulebase
                   :memory memory
                   :transport transport
                   :listeners listeners
                   :get-alphas-fn get-alphas-fn})))
```

**Comment by nrayapati** [comment]
@mrrodriguez  @WilliamParker I know the problem now, the memory being sent to this function was not created with the wrapped activation functions causing that issue, I change my code to the following has fixed the issue. Thanks for the input here. Closing this pull request. 

*Old*:
```clojure
(let [session (dur/assemble-restored-session rulebase
                                            (eng/local-memory rulebase
                                                                (clara.rules.engine.LocalTransport.)
                                                                activation-group-sort-fn
                                                                activation-group-fn
                                                                (dur/create-default-get-alphas-fn rulebase))
                                              opts))))))]
(cr/insert-all session initial-facts))
```
*New*:
```clojure
(let [session (dur/assemble-restored-session rulebase
                                            (eng/local-memory rulebase
                                                                (clara.rules.engine.LocalTransport.)
                                                                (eng/options->activation-group-sort-fn opts)
                                                                (eng/options->activation-group-fn opts)
                                                                (dur/create-default-get-alphas-fn rulebase))
                                              opts))))))]
(cr/insert-all session initial-facts))
```

**Pull request closed without merging**
