### PR TITLE
Issue 225: Batch retractions resulting from external insertions and r…

### PR DESCRIPTION
**Pull request by WilliamParker**
…etractions

### CODE REVIEW

**Comment by rbrush** [comment]
Looks good to me. I'll merge this unless there is anything else you wanted to do here.

**Comment by WilliamParker** [comment]
I think this is ready to merge.  Do you have any concerns @mrrodriguez ?

**Comment by mrrodriguez** [comment]
+1 looks good!

**Comment by rbrush** [comment]
Merged! Thanks, Will! 

Let me know if you guys would like another 0.13.0 RC with this in it. (It's not that much work to push relatively small releases.)

**Pull request merged**
