### PR TITLE
Improve efficiency by using the result of computation

### PR DESCRIPTION
**Pull request by ylando2**

### CODE REVIEW

**Comment by ylando2** [comment]
We previously create a tree structure to describe the dnf but miss the opportunity to connect to the same node from different location, In this way we can describe the exponential structure created by cartesian-join using polynomial number of nodes.
For example we previously turn:
(and (or a1 a2 a3) (or b1 b2 b3) (or c1 c2 c3)) into
(or (and a1 b1 c1) (and a2 b1 c1) ...) one (b1 c1) subexpression for a1,a2,a3.
We could instead connect a1,a2,a3 to (b1 c1) and improve the size and number of step we need to create dnf from exponential to polynomial.

**Comment by mrrodriguez** [comment]
I think we are still having some open discussion/investigation on ways to improve the overall efficiency of worst-case exponential size increase issues.

I just want to chime in that I saw a very little change here that doesn't tackle that whole issue, but does make a big time improvement in `clara.rules.compiler/cartesian-join`.  I think the original PR I saw here hinted at this improvement I think it is a pretty quick win and I could make (if needed) a PR for at least this.

----

`c.r.c/cartesian-join` as implemented:

```clj
(defn- cartesian-join [lists lst]
  (if (seq lists)
    (let [[h & t] lists]
      (mapcat
       (fn [l]
         (map #(conj % l) (cartesian-join t lst))) ; Lots of redundant recursive calls here.
       h))
    [lst]))


;; Perf test it
(time (let [colls (partition 3 (range 66))
            c (range 33)]
        (cartesian-join colls c)
        ;; don't spam
        nil))

;; Has heap space issues - doesn't complete for me with 2gb heap max.

```
-----

Very little change in the interest of time/space wasted:

```clj
(defn- cartesian-join [lists lst]
  (if (seq lists)
    (let [[h & t] lists
          c (cartesian-join t lst)] ; Do the recursion once.
      (mapcat
       (fn [l]
         (map #(conj % l) c)) ; Reuse it each iteration.
       h))
    [lst]))

;; Perf test it
(time (let [colls (partition 3 (range 66))
            c (range 33)]
        (cartesian-join colls c)
        ;; don't spam
        nil))

"Elapsed time: 0.685425 msecs"
;= nil
```

-----

Explanation:

The issue that I noticed here was that the `cartesian-join` recursive call is being made in the body of a `map` nested within a `mapcat`.  However, this could be done a single time and used for all iterations.  This causes significantly more recursive calls and recalculations of the same information.

-----

Side note: 

I think Ryan mentioned it elsewhere, but I think the `cartesian-join` argument names are pretty confusing.  I was definitely confused what it was expecting until doing some prints around it.

**Comment by rbrush** [comment]
I made an attempt to make this a bit easier to understand. The implementation below performs as well as Mike's benchmarks and hopefully is a bit more readable. (I tend to prefer using list comprehensions over nested mapcat and map operations since the flow and variable names seem easier to understand to me.)

I'll probably put this into head since it gives the perf boost Mike was benchmarking and puts us in a better place to continue to improve it. 

Of course, there is a significant opportunity to optimize things outside of this function. At least with this optimization in place I see a lot more time spent in building the beta tree itself rather than converting to disjunctive normal form so that seems like the next place to focus.

```clj
(defn- cartesian-join
  "Performs a cartesian join to distribute disjunctions for disjunctive normal form.,
  This distributing each disjunction across every other disjunction and also across each
  given conjunction. Returns a sequence where each element contains a sequence
  of conjunctions that can be used in rules."
  [disjunctions-to-distribute conjunctions]

  ;; For every disjuction, do a cartesian join to distribute it
  ;; across every other disjuction. We also must distributed it across
  ;; each conjunction
  (reduce
   (fn [distributed-disjunctions disjunction-to-distribute]

     (for [expression disjunction-to-distribute
           distributed-disjunction distributed-disjunctions]
       (conj distributed-disjunction expression)))

   ;; Start with our conjunctions to join to, since we must distribute
   ;; all disjunctions across these as well.
   [conjunctions]
   disjunctions-to-distribute))
```

**Comment by rbrush** [comment]
I did a bit more profiling and with this in place we are spending the bulk of our time in:

1. Comparing and sorting the nodes to generate consistent node IDs across rule executions. I think this might be unnecessary since re-loading a persisted session should produce nodes in the same order, so we can drop this. (Keeping node IDs across sessions only matters anyway for storing and reloading session state, which I don't think is happening much.) We can probably remove this.

2. Building the rete network itself recursively works through and modifies the immutable network structure. (see code in clara.rules.compiler/to-beta-tree and add-to-beta-tree). This will require a bit more effort to optimize, but I think changing to-beta-tree to build a temporary, transient network structure then converting it to an immutable form in a single pass would significantly improve performance.

I think we can add the cartesian-join change and item 1 above pretty easily to a fix release for a quick performance gain if that will be helpful. Re-working the creation of the beta network itself will be more involved, so that seems worth splitting into another item.

Any thoughts are welcome, of course.

**Comment by ylando2** [comment]
Your version of cartesian-join look good. I still think that if we want to remove the exponential part of to-beta-tree, we have two options:
1) Remove the to-dnf, build the beta tree directly from the rule conditions.
2) to-dnf will add a unique id (serial number) for every expression. When we build beta tree we will update a map between id to node in a tree structure that we build before.
If 1 is possible I prefer 1 because it cleaner.

**Comment by rbrush** [comment]
@ylando2 I'm not opposed to removing to-dnf, but converting an arbitrarily complex, nested structure to a beta tree and identifying all commonality introduces a lot of edge cases that don't have clear solutions...and even if they did it's not clear we could handle them faster than building the disjunctive normal form. From what I can tell from the literature and other engines, conversion to disjunctive normal form appears to be very common, presumably for these reasons.

However, there are definitely ways we can optimize this. Between the cartesian-join optimization and another optimization on issue #153, creating the disjunctive normal form is more than 20 times faster for the very "exponential" rule you posted on that issue. I think the next step is to do something similar to your suggestion of a unique id/serial number for every expression when building the beta tree. We already have a unique id of a sort: the identity of the expression itself (in terms of Clojure's identical? function, or a reference comparison in Java). The to-dnf results may include thousands of expressions, but many of these are "identical?" so we could use that when converting it to a network.

Hopefully this seems reasonable! I'm going to track progress on this on #153 and am happy to kick around ideas there.

**Comment by ylando2** [comment]
@rbrush correct me if I am wrong, but Java GC moves the pointers around. So you can check if two expressions are equal by comparing their reference, but you cannot use the reference as the key for a map because they must be constant.

**Comment by rbrush** [comment]
@ylando2 Java can move physical memory locations, but I don't think Java references can change or it would break thinks like java.util.IdentityHashMap (or anyone holding onto a reference value, for that matter). Seems like that IdentityHashMap exists for this type of use case.

**Comment by devn** [comment]
@rbrush I am confident you're correct on your second point regarding beta-tree to/add, and agree that it ought to be split as separate work. Based on some simpleton profiling a few weeks back, I recall seeing beta-related fns stick out in terms of performance. This is partly what spawned a brief discussion in Slack about caching. I simply could not stomach 30-60sec, and so we needed to get fancier with our caching. If that were closer to 5sec than 50sec, it would be easier to justify dropping some reasonable amount of caching complexity.

> "Keeping node IDs across sessions only matters anyway for storing and reloading session state, which I don't think is happening much."

Could you describe in a bit more detail an example scenario that will no longer be possible if node IDs across sessions are no longer kept around across sessions? I'm not clear on the tradeoffs between having and not having it.

**Comment by mrrodriguez** [comment]
Do you happen to know which beta related functions you saw in profiling? I often find paying attention to the type of node it is where you have performance bottlenecks is useful and insightful. Also it is nice to understand if the performance is leaning more towards the (alpha) "insert" or (alpha) "retract" side of things. 

Most often for me, my performance has had a good amount of time within accumulate nodes for example. However there are other cases. Also do you look all the way down the stack and see if you have any reflection warnings or that sort of thing? 

I have been interested is the feasibility of serializing and deserializing whole session state. That is interesting to me for some potential use cases. However the deserialization would need to be pretty quick to be worth it. 

Anyways I don't have the context of your slack conversation. But just curious because I watch performance quite a bit in some of my production usage of Clara as wel. I plan to start listening in on that channel. Sounds like some good conversation is happening there! :P

**Comment by mrrodriguez** [comment]
Or maybe I misread this and the issue is on the time it takes to build the rule session rather than time spent running rules within it.

**Comment by rbrush** [comment]
Consistent node ids across sessions only matters if you are using
clara.rules.durability to serialize and deserialize sessions, since it uses
node ids internally. But I don't think anyone is using this, as the
namespace is marked as still experimental. I think we need to improve our
durability mechanism so this is a non issue, but that's independent of this
issue.

I would encourage taking the code from this branch for a spin in your use
case to see if it helps performance. It makes a huge difference in the
worst case scenario, and I suspect it would help many other cases as well.

**Comment by rbrush** [comment]
A different version of this and a number of optimizations have been included as part of #153. Therefore I'm going to close this one, but we can open another for any further optimizations.

**Pull request closed without merging**
