### PR TITLE
RHS captures all s-expressions using implicit `do`

### PR DESCRIPTION
**Pull request by jonsmock**
Regarding issue #118

### CODE REVIEW

**Comment by jonsmock** [comment]
This was the smallest change I could make to get the desired functionality. Probably better would be to simply return rhs as the captured collection, but doing this caused some problems in parse-rule*, so I backed it out. Let me know if you want me to make that change, and I can take another shot at it. I wanted to at least get this to you for review, and I just had my lunch break to do it.

**Comment by rbrush** [comment]
Yes, I think the minimal approach is the way to go here. We could update parse-rule*, but that's used elsewhere in test code and in a (not publicly available) library that generates rules.

**Comment by rbrush** [comment]
I went ahead and merged this. Thanks for the contribution! We can probably do a fix release with this (and a couple other recent fixes) if desired.

**Comment by jonsmock** [comment]
No problem - thanks for the lib! No rush on the release. We're happily using it as is; I just figured I'd ask/fix it, if ya'll were interested. Seriously, rule engines rock. How did I not know this?! ;-)

**Pull request merged**
