### PR TITLE
Issue 102: Prevent AccumulateNode from creating binding groups when t…

### PR DESCRIPTION
**Pull request by WilliamParker**
…here are no corresponding elements

### CODE REVIEW

**Comment by WilliamParker** [comment]
I've updated this on top of master after the merge of https://github.com/rbrush/clara-rules/pull/206

We can merge this now, after you've looked at it and assuming you agree with the changes of course, and I can then put in tests for this using the new generators later.  Alternatively, we can hold off entirely until generative tests are written; either works.  I'm personally slightly biased toward merging so all work can proceed from the same baseline, but I'm not aware of any work where having these changes in would be particularly beneficial.

**Comment by rbrush** [comment]
I'll get this merged shortly; just poking around it a bit first.

**Comment by WilliamParker** [comment]
No problem, I don't want to pressure you into merging without looking things over first. :)

**Comment by rbrush** [comment]
Alright, merged! Thanks for all of your work on this.

**Pull request merged**
